import { NGO, Post, Fundraiser, VolunteerNeed, NGORegistrationSubmission } from '@/types';

export const INITIAL_NGOS: NGO[] = [
  {
    id: 'ngo-1',
    name: 'Annapurna Seva Mission',
    slug: 'annapurna-seva',
    tagline: 'Zero Hunger in Urban Slums & Migrant Clusters',
    description: 'Serving over 4,500 fresh, nutrient-dense hot meals daily to street children, daily-wage laborers, and elderly citizens across Mumbai & Thane.',
    category: 'Hunger Relief',
    location: 'Mumbai, Maharashtra',
    website: 'https://annapurna-mission.org',
    logo_url: 'https://images.unsplash.com/photo-1541802645635-11f2286a7482?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 98,
    founded_year: 2018,
    reg_number: '80G-MUM-2018-9104',
    pan_number: 'AAATA4421K',
    darpan_id: 'MH/2018/0192841',
  },
  {
    id: 'ngo-2',
    name: 'Vidya Vikas Foundation',
    slug: 'vidya-vikas',
    tagline: 'Bridging the Rural STEM & Digital Literacy Divide',
    description: 'Setting up open-source solar computer labs and coding workshops for adolescent girls in rural Karnataka and Telangana government schools.',
    category: 'Education',
    location: 'Bengaluru, Karnataka',
    website: 'https://vidyavikas-edu.org',
    logo_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 96,
    founded_year: 2016,
    reg_number: '80G-BLR-2016-4421',
    pan_number: 'AABTV9812M',
    darpan_id: 'KA/2016/0104928',
  },
  {
    id: 'ngo-3',
    name: 'Prakriti Green Earth',
    slug: 'prakriti-green',
    tagline: 'Urban Afforestation & Native Lake Rejuvenation',
    description: 'Transforming degraded city dumping yards into dense native Miyawaki micro-forests and restoring traditional wetlands for climate resilience.',
    category: 'Environment',
    location: 'New Delhi, NCR',
    website: 'https://prakriti-earth.org',
    logo_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 94,
    founded_year: 2020,
    reg_number: '80G-DEL-2020-5591',
    pan_number: 'AACCP1192L',
    darpan_id: 'DL/2020/0284719',
  },
  {
    id: 'ngo-4',
    name: 'Jeev Raksha Sanctuary',
    slug: 'jeev-raksha',
    tagline: 'Emergency Trauma Care & Shelter for Street Animals',
    description: 'Operating a 24/7 rescue mobile ambulance service, anti-rabies vaccination clinics, and an orthopedic rehabilitation hospital in Pune.',
    category: 'Animal Welfare',
    location: 'Pune, Maharashtra',
    website: 'https://jeevraksha.org',
    logo_url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 92,
    founded_year: 2019,
    reg_number: '80G-PUN-2019-3312',
    pan_number: 'AAATJ7741R',
    darpan_id: 'MH/2019/0319482',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-2',
    ngo_id: 'ngo-2',
    title: 'Inauguration of 4th Solar STEM Coding Lab in Channapatna',
    content: 'A milestone day! 65 adolescent girls built their first interactive web games using Scratch and Python on refurbished solar-powered laptops. 100% powered by clean energy, eliminating rural power outage interruptions.',
    media_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&auto=format&fit=crop&q=80',
    evidence_images: [
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop',
    ],
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    activity_type: 'past_impact',
    event_date: '2026-09-30',
    location: 'Channapatna Govt High School, Karnataka',
    gps_coordinates: '12.6518° N, 77.2089° E (Govt School Campus)',
    people_reached: 65,
    metrics_label: 'Girls Trained in Python',
    likes_count: 312,
    volunteers_attended: [
      'Karthik Sharma (Lead Coding Tutor)',
      'Meera Nambiar (Python Assistant)',
      'Suresh Patil (Hardware & Solar Tech)',
      'Aarti V. (Student Coordinator)',
    ],
    beneficiary_records: [
      { id: 'b1', name: 'Anjali Gowda', age_or_grade: 'Grade 8', benefit_received: 'Laptop Access & Python Snake Game Project', verification_status: 'Audited' },
      { id: 'b2', name: 'Kavita Rao', age_or_grade: 'Grade 9', benefit_received: 'HTML/CSS Clean Energy Web Page', verification_status: 'Audited' },
      { id: 'b3', name: 'Deepa Naik', age_or_grade: 'Grade 7', benefit_received: 'Scratch Drag-and-Drop Math Logic', verification_status: 'Audited' },
      { id: 'b4', name: 'Pooja Hegde', age_or_grade: 'Grade 9', benefit_received: 'Typing & Digital Communication Certificate', verification_status: 'Audited' },
    ],
    budget_report: {
      total_budget_allocated: 75000,
      total_spent: 74400,
      unspent_balance: 600,
      financial_auditor_note: 'Audited and verified by M/s R.K. Ramanathan & Associates, Chartered Accountants (Mem No: 049182). All invoice vouchers verified against bank disbursals.',
      expenses: [
        {
          id: 'exp-1',
          category: 'Hardware & Educational Devices',
          description: '15 Refurbished ThinkPad Laptops with 256GB SSDs & Linux OS',
          vendor_name: 'ReBoot IT Solutions, Bengaluru',
          invoice_no: 'INV-BLR-2026-9014',
          amount_spent: 52500,
          verified_by_auditor: true,
        },
        {
          id: 'exp-2',
          category: 'Renewable Power Setup',
          description: '1kVA Solar Inverter & LiFePO4 Tubular Battery Pack for Classroom',
          vendor_name: 'Surya Shakti Solar Power, Ramanagara',
          invoice_no: 'INV-SLR-4421',
          amount_spent: 14200,
          verified_by_auditor: true,
        },
        {
          id: 'exp-3',
          category: 'Courseware & Learning Materials',
          description: '65 Spiral Bound Python & Scratch Coding Workbooks in Kannada/English',
          vendor_name: 'Vidya Printers & Book House',
          invoice_no: 'INV-BKS-8812',
          amount_spent: 4800,
          verified_by_auditor: true,
        },
        {
          id: 'exp-4',
          category: 'Logistics & Refreshments',
          description: 'Volunteer transit conveyance & healthy fruit juice boxes for 65 students',
          vendor_name: 'KSRTC Transit + FreshCart Kurla',
          invoice_no: 'VCH-LOG-1102',
          amount_spent: 2900,
          verified_by_auditor: true,
        },
      ],
    },
    created_at: '2026-09-30T14:15:00Z',
  },
  {
    id: 'post-1',
    ngo_id: 'ngo-1',
    title: 'Monsoon Flood Relief: 3,200 Hot Meals Distributed in Dharavi',
    content: 'Following torrential rains and waterlogging, our kitchen mobilized at 4:00 AM. In partnership with 28 community youth volunteers, we distributed khichdi, boiled eggs, hydration salts, and dry rations across transit railway colonies.',
    media_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=80',
    evidence_images: [
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop',
    ],
    activity_type: 'past_impact',
    event_date: '2026-09-28',
    location: 'Dharavi & Sion Transit Colonies, Mumbai',
    gps_coordinates: '19.0434° N, 72.8562° E (Dharavi Transit Camp)',
    people_reached: 3200,
    metrics_label: 'Hot Meals Distributed',
    likes_count: 248,
    volunteers_attended: [
      'Aditya Verma', 'Sunil Pawar', 'Ramesh Yadav', 'Fatima Sheikh', '24 Local Youth'
    ],
    budget_report: {
      total_budget_allocated: 85000,
      total_spent: 84200,
      unspent_balance: 800,
      financial_auditor_note: 'Verified with GST tax invoices from wholesale grain mandis in Navi Mumbai.',
      expenses: [
        {
          id: 'exp-m1',
          category: 'Food Grains & Pulses',
          description: '450kg Rice, 220kg Toor Dal, Multi-Vitamins & Spices',
          vendor_name: 'APMC Market Vashi, Navi Mumbai',
          invoice_no: 'INV-APMC-9901',
          amount_spent: 54000,
          verified_by_auditor: true,
        },
        {
          id: 'exp-m2',
          category: 'Packaging & Hygiene Supplies',
          description: '3,200 Biodegradable Sugarcane Meal Boxes & Cutlery',
          vendor_name: 'EcoPack India Ltd.',
          invoice_no: 'INV-ECO-3312',
          amount_spent: 18200,
          verified_by_auditor: true,
        },
        {
          id: 'exp-m3',
          category: 'Transit Van Fuel & Bottled Water',
          description: '2 Tempo delivery vehicles & 20L Water Jars',
          vendor_name: 'City Logistics Courier',
          invoice_no: 'INV-TRN-771',
          amount_spent: 12000,
          verified_by_auditor: true,
        },
      ],
    },
    created_at: '2026-09-29T10:30:00Z',
  },
  {
    id: 'post-3',
    ngo_id: 'ngo-3',
    title: 'Upcoming: 2,000 Miyawaki Sapling Plantation Drive This Sunday',
    content: 'Join us this Sunday morning at Sector 23 Rohini! We are planting 2,000 indigenous trees (Peepal, Neem, Jamun, Sheesham) to build a dense natural sound and pollution buffer along the outer bypass ring road. Gloves and saplings provided.',
    media_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&auto=format&fit=crop&q=80',
    activity_type: 'upcoming_event',
    event_date: '2026-10-06',
    location: 'Sector 23 Rohini Bypass, New Delhi',
    gps_coordinates: '28.7383° N, 77.0822° E',
    people_reached: 400,
    metrics_label: 'Target Community Volunteers',
    likes_count: 184,
    created_at: '2026-10-01T08:00:00Z',
  },
];

export const INITIAL_FUNDRAISERS: Fundraiser[] = [
  {
    id: 'fund-1',
    ngo_id: 'ngo-1',
    title: 'Sponsor 10,000 Midday Nutrition Packs for Street Children',
    description: 'Ensure 10,000 underprivileged children receive daily immunity-boosting warm meals, iron syrup supplements, and clean drinking water throughout the winter season.',
    target_amount: 250000,
    raised_amount: 184200,
    unit_cost_description: '₹25 provides 1 complete hot nutritious meal',
    status: 'active',
    deadline: '2026-10-31',
    image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-2',
    ngo_id: 'ngo-2',
    title: 'Equip 20 Rural Girls with Coding Laptops & 4G Dongles',
    description: 'Providing refurbished laptops loaded with VS Code, offline Khan Academy modules, and data connectivity so aspiring female coders can prepare for college scholarships.',
    target_amount: 140000,
    raised_amount: 98000,
    unit_cost_description: '₹7,000 funds 1 laptop + 6 months educational broadband',
    status: 'active',
    deadline: '2026-11-15',
    image_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=900&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VOLUNTEER_NEEDS: VolunteerNeed[] = [
  {
    id: 'vol-1',
    ngo_id: 'ngo-1',
    title: 'Weekend Meal Packaging & Dispatch Volunteers',
    description: 'Help our kitchen team pack hygienic meal containers, seal hydration packs, and assist with loading delivery vans across Kurla & Dadar.',
    skills_required: ['Physical Stamina', 'Punctuality', 'Hygiene Care'],
    location: 'Annapurna Central Kitchen, Kurla West, Mumbai',
    event_date: '2026-10-10 07:30 AM',
    total_slots: 20,
    filled_slots: 14,
    status: 'open',
  },
  {
    id: 'vol-2',
    ngo_id: 'ngo-2',
    title: 'Weekend Python & Web Dev Mentors for Class 8-10 Girls',
    description: 'Guide eager young schoolgirls in building simple interactive websites using HTML/CSS or basic Python math puzzles.',
    skills_required: ['Basic Web Dev / Python', 'Patience', 'Fluent in Kannada/Hindi/English'],
    location: 'Channapatna Community STEM Center, Karnataka',
    event_date: '2026-10-11 10:00 AM',
    total_slots: 8,
    filled_slots: 5,
    status: 'open',
  },
];

export const INITIAL_NGO_APPLICATIONS: NGORegistrationSubmission[] = [
  {
    id: 'reg-sub-1',
    name: 'Gramin Aarogya Kendra',
    category: 'Healthcare',
    reg_number: '80G-PUN-2023-1194',
    pan_number: 'AAATG8819Q',
    head_officer_name: 'Dr. Sunita Kulkarni',
    head_officer_phone: '+91 98220 44921',
    official_email: 'contact@graminaarogya.org',
    city: 'Kolhapur, Maharashtra',
    website_or_social: 'https://graminaarogya.org',
    audit_report_url: 'https://storage.example.com/audits/2025-26-report.pdf',
    past_event_proof_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    annual_budget: 1500000,
    status: 'pending_audit',
    submitted_at: '2026-10-01T09:00:00Z',
  }
];
