import { NGO, Post, Fundraiser, VolunteerNeed } from '@/types';

export const INITIAL_NGOS: NGO[] = [
  {
    id: 'ngo-1',
    name: 'Annapurna Seva Mission',
    slug: 'annapurna-seva',
    tagline: 'Zero Hunger in Urban Slums & Migrant Clusters',
    description: 'Serving over 4,500 fresh, nutrient-dense hot meals daily to street children, daily-wage laborers, and elderly citizens across Mumbai & Thane.',
    category: 'Hunger Relief',
    location: 'Mumbai, Maharashtra',
    website: 'https://annapurna-mission.org',
    logo_url: 'https://images.unsplash.com/photo-1541802645635-11f2286a7482?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 98,
    founded_year: 2018,
    reg_number: '80G-MUM-2018-9104',
  },
  {
    id: 'ngo-2',
    name: 'Vidya Vikas Foundation',
    slug: 'vidya-vikas',
    tagline: 'Bridging the Rural STEM & Digital Literacy Divide',
    description: 'Setting up open-source solar computer labs and coding workshops for adolescent girls in rural Karnataka and Telangana government schools.',
    category: 'Education',
    location: 'Bengaluru, Karnataka',
    website: 'https://vidyavikas-edu.org',
    logo_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 96,
    founded_year: 2016,
    reg_number: '80G-BLR-2016-4421',
  },
  {
    id: 'ngo-3',
    name: 'Prakriti Green Earth',
    slug: 'prakriti-green',
    tagline: 'Urban Afforestation & Native Lake Rejuvenation',
    description: 'Transforming degraded city dumping yards into dense native Miyawaki micro-forests and restoring traditional wetlands for climate resilience.',
    category: 'Environment',
    location: 'New Delhi, NCR',
    website: 'https://prakriti-earth.org',
    logo_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 94,
    founded_year: 2020,
    reg_number: '80G-DEL-2020-5591',
  },
  {
    id: 'ngo-4',
    name: 'Jeev Raksha Sanctuary',
    slug: 'jeev-raksha',
    tagline: 'Emergency Trauma Care & Shelter for Street Animals',
    description: 'Operating a 24/7 rescue mobile ambulance service, anti-rabies vaccination clinics, and an orthopedic rehabilitation hospital in Pune.',
    category: 'Animal Welfare',
    location: 'Pune, Maharashtra',
    website: 'https://jeevraksha.org',
    logo_url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    transparency_score: 92,
    founded_year: 2019,
    reg_number: '80G-PUN-2019-3312',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    ngo_id: 'ngo-1',
    title: 'Monsoon Flood Relief: 3,200 Hot Meals Distributed in Dharavi',
    content: 'Following Tuesday’s torrential rains and waterlogging, our kitchen mobilized at 4:00 AM. In partnership with 28 community youth volunteers, we distributed khichdi, boiled eggs, hydration salts, and dry rations across transit railway colonies.',
    media_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-28',
    location: 'Dharavi & Sion, Mumbai',
    people_reached: 3200,
    metrics_label: 'Hot Meals Distributed',
    likes_count: 248,
    created_at: '2026-09-29T10:30:00Z',
  },
  {
    id: 'post-2',
    ngo_id: 'ngo-2',
    title: 'Inauguration of 4th Solar STEM Coding Lab in Channapatna',
    content: 'A milestone day! 65 adolescent girls built their first interactive web games using Scratch and Python on refurbished solar-powered laptops. 100% powered by clean energy, eliminating rural power outage interruptions.',
    media_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-30',
    location: 'Channapatna High School, Karnataka',
    people_reached: 65,
    metrics_label: 'Girls Trained in Python',
    likes_count: 312,
    created_at: '2026-09-30T14:15:00Z',
  },
  {
    id: 'post-3',
    ngo_id: 'ngo-3',
    title: 'Upcoming: 2,000 Miyawaki Sapling Plantation Drive This Sunday',
    content: 'Join us this Sunday morning at Sector 23 Rohini! We are planting 2,000 indigenous trees (Peepal, Neem, Jamun, Sheesham) to build a dense natural sound and pollution buffer along the outer bypass ring road. Gloves and saplings provided.',
    media_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&auto=format&fit=crop&q=80',
    activity_type: 'upcoming_event',
    event_date: '2026-10-06',
    location: 'Sector 23 Rohini Bypass, New Delhi',
    people_reached: 400,
    metrics_label: 'Target Community Volunteers',
    likes_count: 184,
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'post-4',
    ngo_id: 'ngo-4',
    title: 'Miracle Recovery: Sheru Walked Today After 3 Weeks of Therapy!',
    content: 'Sheru was rescued with fractured hind limbs near the highway. Thanks to our orthopedic team and daily hydrotherapy funded by our micro-donors, he took his first unaided steps today! He is now ready for forever adoption.',
    media_url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=900&auto=format&fit=crop&q=80',
    activity_type: 'story',
    event_date: '2026-10-01',
    location: 'Jeev Raksha Hospital, Pune',
    people_reached: 1,
    metrics_label: 'Life Saved & Rehabilitated',
    likes_count: 512,
    created_at: '2026-10-01T16:45:00Z',
  },
];

export const INITIAL_FUNDRAISERS: Fundraiser[] = [
  {
    id: 'fund-1',
    ngo_id: 'ngo-1',
    title: 'Sponsor 10,000 Midday Nutrition Packs for Street Children',
    description: 'Ensure 10,000 underprivileged children receive daily immunity-boosting warm meals, iron syrup supplements, and clean drinking water throughout the winter season.',
    target_amount: 250000,
    raised_amount: 184200,
    unit_cost_description: '₹25 provides 1 complete hot nutritious meal',
    status: 'active',
    deadline: '2026-10-31',
    image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-2',
    ngo_id: 'ngo-2',
    title: 'Equip 20 Rural Girls with Coding Laptops & 4G Dongles',
    description: 'Providing refurbished laptops loaded with VS Code, offline Khan Academy modules, and data connectivity so aspiring female coders can prepare for college scholarships.',
    target_amount: 140000,
    raised_amount: 98000,
    unit_cost_description: '₹7,000 funds 1 laptop + 6 months educational broadband',
    status: 'active',
    deadline: '2026-11-15',
    image_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-3',
    ngo_id: 'ngo-4',
    title: 'Emergency Mobile Ambulance Oxygen & Critical Care Unit',
    description: 'Outfitting our second street animal rescue van with portable oxygen concentrators, digital X-ray scanner, and rapid orthopedic splints to treat hit-and-run animals immediately on-site.',
    target_amount: 180000,
    raised_amount: 122500,
    unit_cost_description: '₹500 covers emergency triage medication for 1 rescued animal',
    status: 'active',
    deadline: '2026-10-25',
    image_url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=900&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VOLUNTEER_NEEDS: VolunteerNeed[] = [
  {
    id: 'vol-1',
    ngo_id: 'ngo-1',
    title: 'Weekend Meal Packaging & Dispatch Volunteers',
    description: 'Help our kitchen team pack hygienic meal containers, seal hydration packs, and assist with loading delivery vans across Kurla & Dadar.',
    skills_required: ['Physical Stamina', 'Punctuality', 'Hygiene Care'],
    location: 'Annapurna Central Kitchen, Kurla West, Mumbai',
    event_date: '2026-10-10 07:30 AM',
    total_slots: 20,
    filled_slots: 14,
    status: 'open',
  },
  {
    id: 'vol-2',
    ngo_id: 'ngo-2',
    title: 'Weekend Python & Web Dev Mentors for Class 8-10 Girls',
    description: 'Guide eager young schoolgirls in building simple interactive websites using HTML/CSS or basic Python math puzzles.',
    skills_required: ['Basic Web Dev / Python', 'Patience', 'Fluent in Kannada/Hindi/English'],
    location: 'Channapatna Community STEM Center, Karnataka',
    event_date: '2026-10-11 10:00 AM',
    total_slots: 8,
    filled_slots: 5,
    status: 'open',
  },
  {
    id: 'vol-3',
    ngo_id: 'ngo-3',
    title: 'Urban Forest Planters & Soil Preparation Volunteers',
    description: 'Hands-on ground planting! Help dig planting pits, mix organic biochar compost, tag native saplings, and lay drip irrigation lines.',
    skills_required: ['Love for Nature', 'Gardening Interest', 'Early Riser'],
    location: 'Sector 23 Wetland Park, Rohini, New Delhi',
    event_date: '2026-10-06 06:30 AM',
    total_slots: 50,
    filled_slots: 36,
    status: 'open',
  },
];
