import { NGO, Post, Fundraiser, VolunteerNeed, StateImpactData } from '@/types';

export const STATE_METRICS: StateImpactData[] = [
  {
    state: 'Maharashtra',
    ngoCount: 125,
    verifiedNgoCount: 98,
    volunteerCount: 2450,
    activeCampaigns: 43,
    peopleReached: 120000,
    fundsRaised: '₹42.8 Lakhs',
    causes: ['Healthcare', 'Education', 'Food', 'Rural Development', 'Environment'],
    districts: ['Pune', 'Mumbai', 'Thane', 'Nashik', 'Nagpur', 'Aurangabad'],
    center: [19.7515, 75.7139],
  },
  {
    state: 'Karnataka',
    ngoCount: 88,
    verifiedNgoCount: 71,
    volunteerCount: 1820,
    activeCampaigns: 29,
    peopleReached: 85000,
    fundsRaised: '₹31.5 Lakhs',
    causes: ['Education', 'Tech Literacy', 'Lake Rejuvenation', 'Healthcare'],
    districts: ['Bengaluru', 'Mysuru', 'Channapatna', 'Mangaluru', 'Hubballi'],
    center: [15.3173, 75.7139],
  },
  {
    state: 'Delhi-NCR',
    ngoCount: 110,
    verifiedNgoCount: 92,
    volunteerCount: 2100,
    activeCampaigns: 38,
    peopleReached: 98000,
    fundsRaised: '₹39.2 Lakhs',
    causes: ['Environment', 'Winter Relief', 'Air Purification', 'Education'],
    districts: ['Central Delhi', 'North Delhi', 'South Delhi', 'Noida', 'Gurugram'],
    center: [28.7041, 77.1025],
  },
  {
    state: 'Gujarat',
    ngoCount: 64,
    verifiedNgoCount: 52,
    volunteerCount: 1240,
    activeCampaigns: 19,
    peopleReached: 62000,
    fundsRaised: '₹24.0 Lakhs',
    causes: ['Water Conservation', 'Healthcare', 'Skill Development'],
    districts: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Kutch'],
    center: [22.2587, 71.1924],
  },
  {
    state: 'Rajasthan',
    ngoCount: 55,
    verifiedNgoCount: 41,
    volunteerCount: 980,
    activeCampaigns: 14,
    peopleReached: 48000,
    fundsRaised: '₹18.5 Lakhs',
    causes: ['Desert Afforestation', 'Girl Child Education', 'Handicrafts'],
    districts: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner'],
    center: [27.0238, 74.2179],
  },
  {
    state: 'Tamil Nadu',
    ngoCount: 72,
    verifiedNgoCount: 59,
    volunteerCount: 1450,
    activeCampaigns: 22,
    peopleReached: 71000,
    fundsRaised: '₹26.4 Lakhs',
    causes: ['Coastal Ecology', 'Disaster Preparedness', 'Elderly Care'],
    districts: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'],
    center: [11.1271, 78.6569],
  },
  {
    state: 'West Bengal',
    ngoCount: 58,
    verifiedNgoCount: 46,
    volunteerCount: 1150,
    activeCampaigns: 17,
    peopleReached: 55000,
    fundsRaised: '₹21.0 Lakhs',
    causes: ['Mangrove Restoration', 'Cyclone Relief', 'Child Welfare'],
    districts: ['Kolkata', 'Sundarbans', 'Howrah', 'Siliguri'],
    center: [22.9868, 87.8550],
  },
  {
    state: 'Bihar',
    ngoCount: 45,
    verifiedNgoCount: 33,
    volunteerCount: 820,
    activeCampaigns: 12,
    peopleReached: 39000,
    fundsRaised: '₹14.2 Lakhs',
    causes: ['Flood Relief', 'Primary Education', 'Rural Nutrition'],
    districts: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur'],
    center: [25.0961, 85.3131],
  },
];

export const INITIAL_NGOS: NGO[] = [
  {
    id: 'ngo-vishwakarma',
    name: 'Vishwakarma Services Foundation',
    slug: 'vishwakarma-services-foundation',
    tagline: 'Empowering Rural Youth, Education & Healthcare in Maharashtra',
    description: 'A grassroots trust dedicated to holistic community transformation across Pune district. Focusing on digital classrooms, mobile medical checkup camps, and technical skill development for marginalized youth.',
    category: 'Education',
    causes: ['Education', 'Healthcare', 'Rural Development'],
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    public_address: 'Survey No. 42, Shivajinagar, Pune, Maharashtra 411005',
    website: 'https://vishwakarma-foundation.org',
    logo_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 99,
    founded_year: 2017,
    reg_number: 'MAH-PUN-2017-8821',
    organization_type: 'Trust',
    renewal_status: 'Active',
    last_renewal_date: '2025-08-15',
    registration_authority: 'Charity Commissioner, Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    active_campaigns_count: 2,
    volunteers_needed_count: 8,
    people_reached_count: 4250,
  },
  {
    id: 'ngo-seva-health',
    name: 'Seva Health Foundation',
    slug: 'seva-health-foundation',
    tagline: 'Primary Healthcare & Diagnostic Camps for Marginalized Urban Clusters',
    description: 'Providing free doctor consultations, mobile pathology testing, eye cataract screenings, and essential medicines to daily-wage workers and children in Mumbai slums.',
    category: 'Healthcare',
    causes: ['Healthcare', 'Disaster Relief'],
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai Suburban',
    city: 'Mumbai',
    public_address: 'Sector 11, Chembur, Mumbai, Maharashtra 400071',
    website: 'https://sevahealth.org',
    logo_url: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 97,
    founded_year: 2019,
    reg_number: 'MAH-MUM-2019-5431',
    organization_type: 'Society',
    renewal_status: 'Active',
    last_renewal_date: '2025-05-10',
    registration_authority: 'Registrar of Societies, Mumbai',
    latitude: 19.0760,
    longitude: 72.8777,
    active_campaigns_count: 2,
    volunteers_needed_count: 12,
    people_reached_count: 8900,
  },
  {
    id: 'ngo-1',
    name: 'Annapurna Seva Mission',
    slug: 'annapurna-seva',
    tagline: 'Zero Hunger in Urban Slums & Migrant Transit Hubs',
    description: 'Serving over 4,500 fresh, nutrient-dense hot meals daily to street children, daily-wage laborers, and elderly citizens across Mumbai & Thane.',
    category: 'Hunger Relief',
    causes: ['Food', 'Healthcare'],
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai City',
    city: 'Mumbai',
    public_address: 'Transit Camp Road, Dharavi, Mumbai 400017',
    website: 'https://annapurna-mission.org',
    logo_url: 'https://images.unsplash.com/photo-1541802645635-11f2286a7482?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 98,
    founded_year: 2018,
    reg_number: '80G-MUM-2018-9104',
    organization_type: 'Trust',
    renewal_status: 'Active',
    last_renewal_date: '2025-09-20',
    registration_authority: 'Charity Commissioner, Mumbai',
    latitude: 19.0400,
    longitude: 72.8500,
    active_campaigns_count: 1,
    volunteers_needed_count: 20,
    people_reached_count: 65000,
  },
  {
    id: 'ngo-2',
    name: 'Vidya Vikas Foundation',
    slug: 'vidya-vikas',
    tagline: 'Bridging the Rural STEM & Digital Literacy Divide',
    description: 'Setting up open-source solar computer labs and coding workshops for adolescent girls in rural Karnataka and Telangana government schools.',
    category: 'Education',
    causes: ['Education', 'Women Empowerment'],
    location: 'Bengaluru, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    public_address: '100ft Road, Indiranagar, Bengaluru 560038',
    website: 'https://vidyavikas-edu.org',
    logo_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 96,
    founded_year: 2016,
    reg_number: '80G-BLR-2016-4421',
    organization_type: 'Section 8 Company',
    renewal_status: 'Active',
    last_renewal_date: '2025-11-01',
    registration_authority: 'Registrar of Companies, Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    active_campaigns_count: 1,
    volunteers_needed_count: 8,
    people_reached_count: 12200,
  },
  {
    id: 'ngo-3',
    name: 'Prakriti Green Earth',
    slug: 'prakriti-green',
    tagline: 'Urban Afforestation & Native Lake Rejuvenation',
    description: 'Transforming degraded city dumping yards into dense native Miyawaki micro-forests and restoring traditional wetlands for climate resilience.',
    category: 'Environment',
    causes: ['Environment'],
    location: 'New Delhi, NCR',
    state: 'Delhi-NCR',
    district: 'North West Delhi',
    city: 'New Delhi',
    public_address: 'Sector 23, Rohini Bypass, New Delhi 110085',
    website: 'https://prakriti-earth.org',
    logo_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 94,
    founded_year: 2020,
    reg_number: '80G-DEL-2020-5591',
    organization_type: 'Society',
    renewal_status: 'Active',
    last_renewal_date: '2025-04-12',
    registration_authority: 'Registrar of Societies, Delhi',
    latitude: 28.7041,
    longitude: 77.1025,
    active_campaigns_count: 1,
    volunteers_needed_count: 50,
    people_reached_count: 18000,
  },
  {
    id: 'ngo-4',
    name: 'Jeev Raksha Sanctuary',
    slug: 'jeev-raksha',
    tagline: 'Emergency Trauma Care & Shelter for Street Animals',
    description: 'Operating a 24/7 rescue mobile ambulance service, anti-rabies vaccination clinics, and an orthopedic rehabilitation hospital in Pune.',
    category: 'Animal Welfare',
    causes: ['Animal Welfare'],
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    public_address: 'Katraj Bypass, Pune, Maharashtra 411046',
    website: 'https://jeevraksha.org',
    logo_url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=160&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=1200&auto=format&fit=crop&q=80',
    verified: true,
    verification_status: 'platform_verified',
    transparency_score: 92,
    founded_year: 2019,
    reg_number: '80G-PUN-2019-3312',
    organization_type: 'Trust',
    renewal_status: 'Active',
    last_renewal_date: '2025-06-30',
    registration_authority: 'Charity Commissioner, Pune',
    latitude: 18.4529,
    longitude: 73.8652,
    active_campaigns_count: 1,
    volunteers_needed_count: 6,
    people_reached_count: 3100,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-vishwakarma-1',
    ngo_id: 'ngo-vishwakarma',
    title: 'School Supply Kits Distributed to 500 Students in Junnar Rural School',
    content: 'Our team completed the distribution of 500 comprehensive school kits containing textbooks, notebooks, geometric sets, and school bags to children across Junnar tribal block. Complete utilization receipts and GPS photo verification logged on platform.',
    media_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-28',
    location: 'Junnar Block, Pune District, Maharashtra',
    people_reached: 450,
    metrics_label: 'Students Reached with Kits',
    likes_count: 342,
    created_at: '2026-09-29T08:30:00Z',
  },
  {
    id: 'post-seva-1',
    ngo_id: 'ngo-seva-health',
    title: 'Free Cataract Screening & Medical Camp for 600 Senior Citizens',
    content: 'In collaboration with volunteer ophthalmologists, we conducted our monthly preventive eye care drive in Chembur. 68 cataract surgeries were successfully scheduled free of cost at our partner hospital.',
    media_url: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-27',
    location: 'Chembur Community Center, Mumbai',
    people_reached: 600,
    metrics_label: 'Senior Citizens Screened',
    likes_count: 275,
    created_at: '2026-09-28T11:00:00Z',
  },
  {
    id: 'post-1',
    ngo_id: 'ngo-1',
    title: 'Monsoon Flood Relief: 3,200 Hot Meals Distributed in Dharavi',
    content: 'Following Tuesday’s torrential rains and waterlogging, our kitchen mobilized at 4:00 AM. In partnership with 28 community youth volunteers, we distributed khichdi, boiled eggs, hydration salts, and dry rations across transit railway colonies.',
    media_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-28',
    location: 'Dharavi & Sion, Mumbai',
    people_reached: 3200,
    metrics_label: 'Hot Meals Distributed',
    likes_count: 248,
    created_at: '2026-09-29T10:30:00Z',
  },
  {
    id: 'post-2',
    ngo_id: 'ngo-2',
    title: 'Inauguration of 4th Solar STEM Coding Lab in Channapatna',
    content: 'A milestone day! 65 adolescent girls built their first interactive web games using Scratch and Python on refurbished solar-powered laptops. 100% powered by clean energy, eliminating rural power outage interruptions.',
    media_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&auto=format&fit=crop&q=80',
    activity_type: 'past_impact',
    event_date: '2026-09-30',
    location: 'Channapatna High School, Karnataka',
    people_reached: 65,
    metrics_label: 'Girls Trained in Python',
    likes_count: 312,
    created_at: '2026-09-30T14:15:00Z',
  },
  {
    id: 'post-3',
    ngo_id: 'ngo-3',
    title: 'Upcoming: 2,000 Miyawaki Sapling Plantation Drive This Sunday',
    content: 'Join us this Sunday morning at Sector 23 Rohini! We are planting 2,000 indigenous trees (Peepal, Neem, Jamun, Sheesham) to build a dense natural sound and pollution buffer along the outer bypass ring road. Gloves and saplings provided.',
    media_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&auto=format&fit=crop&q=80',
    activity_type: 'upcoming_event',
    event_date: '2026-10-06',
    location: 'Sector 23 Rohini Bypass, New Delhi',
    people_reached: 400,
    metrics_label: 'Target Community Volunteers',
    likes_count: 184,
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'post-4',
    ngo_id: 'ngo-4',
    title: 'Miracle Recovery: Sheru Walked Today After 3 Weeks of Therapy!',
    content: 'Sheru was rescued with fractured hind limbs near the highway. Thanks to our orthopedic team and daily hydrotherapy funded by our micro-donors, he took his first unaided steps today! He is now ready for forever adoption.',
    media_url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=900&auto=format&fit=crop&q=80',
    activity_type: 'story',
    event_date: '2026-10-01',
    location: 'Jeev Raksha Hospital, Pune',
    people_reached: 1,
    metrics_label: 'Life Saved & Rehabilitated',
    likes_count: 512,
    created_at: '2026-10-01T16:45:00Z',
  },
];

export const INITIAL_FUNDRAISERS: Fundraiser[] = [
  {
    id: 'fund-vishwakarma-1',
    ngo_id: 'ngo-vishwakarma',
    title: 'School Supplies & STEM Learning Kits for 500 Students',
    description: 'Target: ₹1,00,000. Raised: ₹72,500. Utilized: ₹58,000. Remaining: ₹14,500. Direct utilization voucher breakdown: Books ₹25,000, School Bags ₹20,000, Stationery ₹13,000. 500 kits delivered to 450 verified rural students.',
    target_amount: 100000,
    raised_amount: 72500,
    unit_cost_description: '₹200 sponsors 1 student full year kit',
    status: 'active',
    deadline: '2026-11-10',
    image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-seva-1',
    ngo_id: 'ngo-seva-health',
    title: 'Primary Health Care Clinic & Medicine Subsidies',
    description: 'Provide subsidised diagnostic tests and free diabetic/hypertension medications for 800 slum families living below the poverty line.',
    target_amount: 80000,
    raised_amount: 54000,
    unit_cost_description: '₹150 covers 1 month essential hypertension medicine',
    status: 'active',
    deadline: '2026-11-05',
    image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-1',
    ngo_id: 'ngo-1',
    title: 'Sponsor 10,000 Midday Nutrition Packs for Street Children',
    description: 'Ensure 10,000 underprivileged children receive daily immunity-boosting warm meals, iron syrup supplements, and clean drinking water throughout the winter season.',
    target_amount: 250000,
    raised_amount: 184200,
    unit_cost_description: '₹25 provides 1 complete hot nutritious meal',
    status: 'active',
    deadline: '2026-10-31',
    image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-2',
    ngo_id: 'ngo-2',
    title: 'Equip 20 Rural Girls with Coding Laptops & 4G Dongles',
    description: 'Providing refurbished laptops loaded with VS Code, offline Khan Academy modules, and data connectivity so aspiring female coders can prepare for college scholarships.',
    target_amount: 140000,
    raised_amount: 98000,
    unit_cost_description: '₹7,000 funds 1 laptop + 6 months educational broadband',
    status: 'active',
    deadline: '2026-11-15',
    image_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=900&auto=format&fit=crop&q=80',
  },
  {
    id: 'fund-3',
    ngo_id: 'ngo-4',
    title: 'Emergency Mobile Ambulance Oxygen & Critical Care Unit',
    description: 'Outfitting our second street animal rescue van with portable oxygen concentrators, digital X-ray scanner, and rapid orthopedic splints to treat hit-and-run animals immediately on-site.',
    target_amount: 180000,
    raised_amount: 122500,
    unit_cost_description: '₹500 covers emergency triage medication for 1 rescued animal',
    status: 'active',
    deadline: '2026-10-25',
    image_url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=900&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VOLUNTEER_NEEDS: VolunteerNeed[] = [
  {
    id: 'vol-vishwakarma-1',
    ngo_id: 'ngo-vishwakarma',
    title: '8 Field Volunteers for Rural School STEM & Kit Distribution',
    description: 'Travel to Junnar school block to unpack kits, conduct basic interactive science demonstrations, and assist teachers with student attendance logs.',
    skills_required: ['Teaching', 'Marathi / Hindi Communication', 'Basic Science'],
    location: 'Junnar Rural School, Pune District, Maharashtra',
    event_date: '2026-10-18 09:00 AM',
    total_slots: 8,
    filled_slots: 0,
    status: 'open',
  },
  {
    id: 'vol-seva-1',
    ngo_id: 'ngo-seva-health',
    title: '12 Volunteers for Community Health Camp & Patient Registration',
    description: 'Manage registration desks, assist elderly patients with mobility, and distribute pre-packaged medicine kits under doctor supervision.',
    skills_required: ['Empathy', 'Hindi / Marathi', 'Patience'],
    location: 'Chembur East Community Hall, Mumbai',
    event_date: '2026-10-19 08:30 AM',
    total_slots: 12,
    filled_slots: 4,
    status: 'open',
  },
  {
    id: 'vol-1',
    ngo_id: 'ngo-1',
    title: 'Weekend Meal Packaging & Dispatch Volunteers',
    description: 'Help our kitchen team pack hygienic meal containers, seal hydration packs, and assist with loading delivery vans across Kurla & Dadar.',
    skills_required: ['Physical Stamina', 'Punctuality', 'Hygiene Care'],
    location: 'Annapurna Central Kitchen, Kurla West, Mumbai',
    event_date: '2026-10-10 07:30 AM',
    total_slots: 20,
    filled_slots: 14,
    status: 'open',
  },
  {
    id: 'vol-2',
    ngo_id: 'ngo-2',
    title: 'Weekend Python & Web Dev Mentors for Class 8-10 Girls',
    description: 'Guide eager young schoolgirls in building simple interactive websites using HTML/CSS or basic Python math puzzles.',
    skills_required: ['Basic Web Dev / Python', 'Patience', 'Fluent in Kannada/Hindi/English'],
    location: 'Channapatna Community STEM Center, Karnataka',
    event_date: '2026-10-11 10:00 AM',
    total_slots: 8,
    filled_slots: 5,
    status: 'open',
  },
  {
    id: 'vol-3',
    ngo_id: 'ngo-3',
    title: 'Urban Forest Planters & Soil Preparation Volunteers',
    description: 'Hands-on ground planting! Help dig planting pits, mix organic biochar compost, tag native saplings, and lay drip irrigation lines.',
    skills_required: ['Love for Nature', 'Gardening Interest', 'Early Riser'],
    location: 'Sector 23 Wetland Park, Rohini, New Delhi',
    event_date: '2026-10-06 06:30 AM',
    total_slots: 50,
    filled_slots: 36,
    status: 'open',
  },
];
